site_name: Elias MKDOCS
site_url: https://github.com/eliasxvv16/ejercicio4
site_dir: site


nav: 
- Home: index.md 
- Ejercicio1: Ejercicio1.md
- Ejercicio2: Ejercicio2.md
- Ejercicio3: Ejercicio3.md

theme: readthedocs