site_name: Documentaci√≥n Elias Halloumi El Amraoui
site_url: https://eliasxvv16.github.io/ejercicio4/
site_dir: /docs

nav:
  - Inicio: index.md
  - Minima: ejercicio1.md
  - lagrange: ejercicio2.md
  - P-resume: ejercicio3.md
theme: readthedocs  