site_name: Mkdocs Elias
site_url: https://eliasxvv16.github.io/ejercicio4/
site_dir: site

nav:
  - Inicio: index.md
  - Minima: ejercicio1.md
  - lagrange: ejercicio2.md
  - P-Resume: ejercicio3.md
theme: material  # o 'material' si instalas mkdocs-material