site_name: Documentaci√≥n eliasxvv16
site_url: https://eliasxvv16.github.io/ejercicio4/
docs_dir: docs
site_dir: site

nav:
  - Inicio: index.md
  - Minima: ejercicio1.md
  - lagrange: ejercicio2.md
  - Satelite: ejercicio3.md
theme: readthedocs  